In [1]:
##libraries used tensorflow > 2.0 and keras

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
###sentences
sent = ["I am a good girl",
       "I love my mother the most",
       "my brother is super naughty",
       "my dad is super hero",
       "the cup of tea"]

In [7]:
sent


['I am a good girl',
 'I love my mother the most',
 'my brother is super naughty',
 'my dad is super hero',
 'the cup of tea']

In [8]:
voc_size = 10000

# One hot Representations

In [9]:
#This gives the index from the dictionary
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[1376, 1655, 3198, 3873, 9255], [1376, 2949, 3696, 1271, 8896, 1194], [3696, 9594, 1242, 2429, 4646], [3696, 2766, 1242, 2429, 1918], [8896, 1319, 2240, 9884]]


# word embedding representation

In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np

In [17]:
sent_length = 7
embedded_docs = pad_sequences(onehot_repr,padding="pre",maxlen = sent_length)
embedded_docs

array([[   0,    0, 1376, 1655, 3198, 3873, 9255],
       [   0, 1376, 2949, 3696, 1271, 8896, 1194],
       [   0,    0, 3696, 9594, 1242, 2429, 4646],
       [   0,    0, 3696, 2766, 1242, 2429, 1918],
       [   0,    0,    0, 8896, 1319, 2240, 9884]])

In [18]:
##dimensions is features
dim= 10

In [19]:
##embedding converts into featurized representation using dimensions
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile("adam",'mse')
#adam optimizer
#mse performance metrics

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 7, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.predict(embedded_docs)

array([[[ 1.1771906e-02, -3.1540919e-02, -3.9691828e-02, -1.4668096e-02,
         -7.5317509e-03, -1.4597118e-02, -2.1909893e-02,  2.0346496e-02,
          4.7788624e-02,  4.4250581e-02],
        [ 1.1771906e-02, -3.1540919e-02, -3.9691828e-02, -1.4668096e-02,
         -7.5317509e-03, -1.4597118e-02, -2.1909893e-02,  2.0346496e-02,
          4.7788624e-02,  4.4250581e-02],
        [ 4.3115392e-03,  3.1844378e-03, -1.3748072e-02, -2.8885400e-02,
         -7.2374456e-03, -4.1530885e-02,  3.9558444e-02,  2.4080779e-02,
          4.7076229e-02,  3.1918850e-02],
        [ 1.5385870e-02,  5.7246201e-03, -4.3096673e-02, -1.4275491e-02,
         -2.5353543e-03, -1.8592097e-02, -4.5729723e-02, -3.3169307e-02,
         -3.8005747e-02,  2.3824945e-03],
        [-1.9320369e-02,  3.6354456e-02, -6.9773309e-03,  4.3807697e-02,
         -4.1747224e-02, -3.0633045e-02, -2.9918814e-02, -1.7790508e-02,
         -3.7854206e-02,  4.6027545e-02],
        [-3.3148408e-02, -7.1484074e-03, -5.0094947e-03,  3.

In [22]:
embedded_docs[0]

array([   0,    0, 1376, 1655, 3198, 3873, 9255])

In [23]:
model.predict(embedded_docs)[0]

array([[ 0.01177191, -0.03154092, -0.03969183, -0.0146681 , -0.00753175,
        -0.01459712, -0.02190989,  0.0203465 ,  0.04778862,  0.04425058],
       [ 0.01177191, -0.03154092, -0.03969183, -0.0146681 , -0.00753175,
        -0.01459712, -0.02190989,  0.0203465 ,  0.04778862,  0.04425058],
       [ 0.00431154,  0.00318444, -0.01374807, -0.0288854 , -0.00723745,
        -0.04153088,  0.03955844,  0.02408078,  0.04707623,  0.03191885],
       [ 0.01538587,  0.00572462, -0.04309667, -0.01427549, -0.00253535,
        -0.0185921 , -0.04572972, -0.03316931, -0.03800575,  0.00238249],
       [-0.01932037,  0.03635446, -0.00697733,  0.0438077 , -0.04174722,
        -0.03063305, -0.02991881, -0.01779051, -0.03785421,  0.04602754],
       [-0.03314841, -0.00714841, -0.00500949,  0.03635634, -0.04847456,
         0.02191437,  0.02209163, -0.02711006, -0.03188298, -0.038087  ],
       [ 0.0405624 , -0.01837435,  0.03884817,  0.00960709, -0.04566767,
        -0.01934046, -0.03215803, -0.03582048

In [24]:
##each word in the sentences is converted to featurized vector 
##using 10 features